# Generated by Django 3.0.8 on 2020-08-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_activities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
