# Generated by Django 3.0.8 on 2020-08-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_activities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
